[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = true
git_release_enable = true
git_tag_enable = true
publish = false
release_always = false
release_commits = "^(feat|fix|perf|revert)(\\(.+\\))?:"
