use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::{CommandFactory, Parser, Subcommand, ValueEnum};
use clap_complete::Shell;

mod checks;
mod config;
mod core;
mod github;
mod profiles;
mod report;

pub use profiles::Profile;
pub use report::RunOutput;

#[derive(Debug, Parser)]
#[command(author, version, about)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Check repository hygiene.
    Check {
        /// Repository directory to inspect.
        #[arg(default_value = ".")]
        path: PathBuf,

        /// Output format.
        #[arg(short, long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,

        /// Profile to run.
        #[arg(long, value_enum, default_value_t = Profile::Auto)]
        profile: Profile,

        /// Config file path. Defaults to repo-doctor.toml in the repository root.
        #[arg(long)]
        config: Option<PathBuf>,

        /// Baseline JSON generated by `repo-doctor baseline`.
        #[arg(long)]
        baseline: Option<PathBuf>,

        /// Emit only warning checks.
        #[arg(long)]
        warnings_only: bool,

        /// Exit nonzero when the report score is below this percentage.
        #[arg(long, value_parser = clap::value_parser!(u8).range(0..=100))]
        min_score: Option<u8>,

        /// Exit nonzero when the report contains findings at this level.
        #[arg(long, value_enum)]
        fail_on: Option<FailOn>,
    },

    /// Create a starter repo-doctor.toml.
    Init {
        /// Repository directory where repo-doctor.toml should be written.
        #[arg(default_value = ".")]
        path: PathBuf,

        /// Also create common support files when they are missing.
        #[arg(long)]
        full: bool,
    },

    /// Create a baseline JSON containing current warning rule IDs.
    Baseline {
        /// Repository directory to inspect.
        #[arg(default_value = ".")]
        path: PathBuf,
    },

    /// Run checks for every repository path listed in a file.
    Batch {
        /// File containing one repository path per line.
        input: PathBuf,
    },

    /// Explain a rule ID.
    Explain {
        /// Rule ID to explain.
        rule_id: String,
    },

    /// Validate a repo-doctor.toml file.
    ConfigValidate {
        /// Config file path.
        #[arg(default_value = "repo-doctor.toml")]
        path: PathBuf,
    },

    /// Run remote GitHub repository checks using the gh CLI.
    Github {
        /// GitHub repository in owner/name form.
        repo: String,

        /// Output format.
        #[arg(short, long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,

        /// Emit only warning checks.
        #[arg(long)]
        warnings_only: bool,
    },

    /// Apply common remote GitHub settings using the gh CLI.
    GithubSetup {
        /// GitHub repository in owner/name form.
        repo: String,

        /// Topic to add. Repeat for multiple topics.
        #[arg(long = "topic")]
        topics: Vec<String>,

        /// Homepage URL to set.
        #[arg(long)]
        homepage: Option<String>,

        /// Enable default branch protection.
        #[arg(long)]
        branch_protection: bool,
    },

    /// List supported profiles and auto-detection hints.
    ListProfiles,

    /// List known rule IDs for configuration.
    ListRules,

    /// Generate shell completion scripts.
    Completions {
        /// Shell to generate completions for.
        shell: Shell,
    },

    /// Generate a manual page.
    Man,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum OutputFormat {
    Text,
    Json,
    Markdown,
    Github,
    Sarif,
    Compact,
    Junit,
    Html,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum FailOn {
    Warn,
}

pub fn run(cli: Cli) -> Result<RunOutput> {
    match cli.command {
        Command::Check {
            path,
            format,
            profile,
            config,
            baseline,
            warnings_only,
            min_score,
            fail_on,
        } => check_repository_with_options(
            &path,
            format,
            profile,
            config.as_deref(),
            CheckOptions {
                fail_on,
                warnings_only,
                min_score,
                baseline: baseline.as_deref(),
            },
        ),
        Command::Init { path, full } => init_config(&path, full),
        Command::Baseline { path } => create_baseline(&path),
        Command::Batch { input } => batch_check(&input),
        Command::Explain { rule_id } => explain_rule(&rule_id),
        Command::ConfigValidate { path } => validate_config_file(&path),
        Command::Github {
            repo,
            format,
            warnings_only,
        } => check_github_repository_with_options(
            &repo,
            format,
            CheckOptions {
                fail_on: None,
                warnings_only,
                min_score: None,
                baseline: None,
            },
        ),
        Command::GithubSetup {
            repo,
            topics,
            homepage,
            branch_protection,
        } => github_setup(&repo, &topics, homepage.as_deref(), branch_protection),
        Command::ListProfiles => Ok(RunOutput {
            text: list_profiles(),
            exit_code: 0,
        }),
        Command::ListRules => Ok(RunOutput {
            text: list_rules(),
            exit_code: 0,
        }),
        Command::Completions { shell } => Ok(RunOutput {
            text: completions(shell)?,
            exit_code: 0,
        }),
        Command::Man => Ok(RunOutput {
            text: man_page()?,
            exit_code: 0,
        }),
    }
}

pub fn check_repository(
    path: &Path,
    format: OutputFormat,
    profile: Profile,
    fail_on: Option<FailOn>,
) -> Result<RunOutput> {
    check_repository_with_config(path, format, profile, None, fail_on)
}

pub fn check_repository_with_config(
    path: &Path,
    format: OutputFormat,
    profile: Profile,
    config_path: Option<&Path>,
    fail_on: Option<FailOn>,
) -> Result<RunOutput> {
    check_repository_with_options(
        path,
        format,
        profile,
        config_path,
        CheckOptions {
            fail_on,
            warnings_only: false,
            min_score: None,
            baseline: None,
        },
    )
}

#[derive(Clone, Copy, Debug, Default)]
struct CheckOptions<'a> {
    fail_on: Option<FailOn>,
    warnings_only: bool,
    min_score: Option<u8>,
    baseline: Option<&'a Path>,
}

fn check_repository_with_options(
    path: &Path,
    format: OutputFormat,
    profile: Profile,
    config_path: Option<&Path>,
    options: CheckOptions<'_>,
) -> Result<RunOutput> {
    validate_repository_path(path)?;

    let config = config::load(path, config_path)?;
    let mut report = inspect_repository_with_config(path, profile, &config);
    if let Some(baseline) = options.baseline {
        let ignored = read_baseline(baseline)?;
        report = report.suppress_warning_ids(&ignored);
    }
    let exit_code = if (options.fail_on == Some(FailOn::Warn) && report.has_warnings())
        || options
            .min_score
            .is_some_and(|min_score| report.score() < min_score)
    {
        1
    } else {
        0
    };
    let report = if options.warnings_only {
        report.warnings_only()
    } else {
        report
    };

    let text = match format {
        OutputFormat::Text => report.format_text(),
        OutputFormat::Json => serde_json::to_string_pretty(&report)?,
        OutputFormat::Markdown => report.format_markdown(),
        OutputFormat::Github => report.format_github_annotations(),
        OutputFormat::Sarif => report.format_sarif()?,
        OutputFormat::Compact => report.format_compact(),
        OutputFormat::Junit => report.format_junit(),
        OutputFormat::Html => report.format_html(),
    };

    Ok(RunOutput { text, exit_code })
}

pub fn inspect_repository(path: &Path, profile: Profile) -> report::Report {
    inspect_repository_with_config(path, profile, &config::Config::default())
}

fn inspect_repository_with_config(
    path: &Path,
    profile: Profile,
    config: &config::Config,
) -> report::Report {
    let mut checks = core::inspect(path);
    let selected_profiles = config.selected_profiles(path, profile);
    checks.extend(profiles::inspect(path, &selected_profiles));
    checks = config.apply(checks);

    report::Report::new(path.to_path_buf(), selected_profiles, checks)
}

pub fn init_config(path: &Path, full: bool) -> Result<RunOutput> {
    validate_repository_path(path)?;

    let config_path = path.join("repo-doctor.toml");
    if config_path.exists() && !full {
        bail!("config already exists: {}", config_path.display());
    }

    let mut created = Vec::new();
    if !config_path.exists() {
        std::fs::write(&config_path, config::STARTER_CONFIG)?;
        created.push(config_path.display().to_string());
    }

    if full {
        created.extend(init_full(path)?);
    }

    Ok(RunOutput {
        text: if created.is_empty() {
            "No files created; everything already exists".to_owned()
        } else {
            format!("Created:\n{}", created.join("\n"))
        },
        exit_code: 0,
    })
}

fn init_full(path: &Path) -> Result<Vec<String>> {
    let files = [
        (
            ".editorconfig",
            "root = true\n\n[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\nindent_style = space\nindent_size = 4\n",
        ),
        (".gitattributes", "* text=auto eol=lf\n"),
        (".env.example", "RUST_LOG=info\n"),
        (
            ".github/dependabot.yml",
            "version: 2\nupdates:\n  - package-ecosystem: cargo\n    directory: /\n    schedule:\n      interval: weekly\n",
        ),
        (
            ".github/workflows/ci.yml",
            "name: CI\non:\n  push:\n  pull_request:\npermissions:\n  contents: read\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v6\n      - uses: dtolnay/rust-toolchain@stable\n      - run: cargo fmt --all --check\n      - run: cargo clippy --all-targets --all-features -- -D warnings\n      - run: cargo test\n",
        ),
    ];
    let mut created = Vec::new();

    for (relative, contents) in files {
        let target = path.join(relative);
        if target.exists() {
            continue;
        }
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&target, contents)?;
        created.push(target.display().to_string());
    }

    Ok(created)
}

pub fn check_github_repository(repo: &str, format: OutputFormat) -> Result<RunOutput> {
    check_github_repository_with_options(repo, format, CheckOptions::default())
}

fn check_github_repository_with_options(
    repo: &str,
    format: OutputFormat,
    options: CheckOptions<'_>,
) -> Result<RunOutput> {
    let report = github::inspect(repo)?;
    let report = if options.warnings_only {
        report.warnings_only()
    } else {
        report
    };
    let text = match format {
        OutputFormat::Text => report.format_text(),
        OutputFormat::Json => serde_json::to_string_pretty(&report)?,
        OutputFormat::Markdown => report.format_markdown(),
        OutputFormat::Github => report.format_github_annotations(),
        OutputFormat::Sarif => report.format_sarif()?,
        OutputFormat::Compact => report.format_compact(),
        OutputFormat::Junit => report.format_junit(),
        OutputFormat::Html => report.format_html(),
    };

    Ok(RunOutput { text, exit_code: 0 })
}

pub fn list_profiles() -> String {
    Profile::catalog()
        .iter()
        .map(|(profile, hint)| format!("{profile}\t{hint}"))
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn list_rules() -> String {
    report::known_rules()
        .iter()
        .map(|rule| format!("{}\t{}\t{}", rule.id, rule.severity, rule.description))
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn explain_rule(rule_id: &str) -> Result<RunOutput> {
    let Some(rule) = report::known_rules().iter().find(|rule| rule.id == rule_id) else {
        bail!("unknown rule id: {rule_id}");
    };

    Ok(RunOutput {
        text: format!(
            "Rule: {}\nSeverity: {}\nPurpose: {}\nRemediation: Run `repo-doctor check --warnings-only` for concrete findings, or disable this rule in repo-doctor.toml with a rationale when it does not apply.",
            rule.id, rule.severity, rule.description
        ),
        exit_code: 0,
    })
}

pub fn validate_config_file(path: &Path) -> Result<RunOutput> {
    let findings = config::validate(path)?;
    if findings.is_empty() {
        Ok(RunOutput {
            text: format!("{} is valid", path.display()),
            exit_code: 0,
        })
    } else {
        Ok(RunOutput {
            text: findings.join("\n"),
            exit_code: 1,
        })
    }
}

pub fn create_baseline(path: &Path) -> Result<RunOutput> {
    validate_repository_path(path)?;
    let report = inspect_repository(path, Profile::Auto);
    let ids = report.warning_ids();

    Ok(RunOutput {
        text: serde_json::to_string_pretty(&ids)?,
        exit_code: 0,
    })
}

fn read_baseline(path: &Path) -> Result<Vec<String>> {
    let contents = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read baseline: {}", path.display()))?;
    serde_json::from_str(&contents)
        .with_context(|| format!("failed to parse baseline: {}", path.display()))
}

pub fn batch_check(input: &Path) -> Result<RunOutput> {
    let contents = std::fs::read_to_string(input)
        .with_context(|| format!("failed to read batch input: {}", input.display()))?;
    let mut lines = Vec::new();
    let mut exit_code = 0;

    for entry in contents.lines().map(str::trim) {
        if entry.is_empty() || entry.starts_with('#') {
            continue;
        }
        let path = Path::new(entry);
        match check_repository(
            path,
            OutputFormat::Compact,
            Profile::Auto,
            Some(FailOn::Warn),
        ) {
            Ok(output) => {
                if output.exit_code != 0 {
                    exit_code = 1;
                }
                lines.push(output.text);
            }
            Err(error) => {
                exit_code = 1;
                lines.push(format!("repo-doctor path={entry} error={error}"));
            }
        }
    }

    Ok(RunOutput {
        text: lines.join("\n"),
        exit_code,
    })
}

pub fn github_setup(
    repo: &str,
    topics: &[String],
    homepage: Option<&str>,
    branch_protection: bool,
) -> Result<RunOutput> {
    let actions = github::setup(repo, topics, homepage, branch_protection)?;

    Ok(RunOutput {
        text: if actions.is_empty() {
            "No GitHub setup actions requested".to_owned()
        } else {
            actions.join("\n")
        },
        exit_code: 0,
    })
}

fn validate_repository_path(path: &Path) -> Result<()> {
    if !path.exists() {
        bail!("repository path does not exist: {}", path.display());
    }

    if !path.is_dir() {
        bail!("repository path is not a directory: {}", path.display());
    }

    Ok(())
}

pub fn completions(shell: Shell) -> Result<String> {
    let mut command = Cli::command();
    let name = command.get_name().to_owned();
    let mut buffer = Vec::new();

    clap_complete::generate(shell, &mut command, name, &mut buffer);

    Ok(String::from_utf8(buffer)?)
}

pub fn man_page() -> Result<String> {
    let command = Cli::command();
    let man = clap_mangen::Man::new(command);
    let mut buffer = Vec::new();

    man.render(&mut buffer)?;

    Ok(String::from_utf8(buffer)?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn auto_profile_runs_rust_checks_when_cargo_toml_exists() {
        let temp_dir = tempfile::tempdir().unwrap();
        write_rust_fixture(temp_dir.path());

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[PASS] readme: README is present"));
        assert!(output.text.contains("Profiles: rust"));
        assert!(output.text.contains("Summary:"));
        assert!(
            output
                .text
                .contains("[PASS] rust_cargo_name: Cargo package `name` is set")
        );
    }

    #[test]
    fn generic_profile_skips_rust_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        write_rust_fixture(temp_dir.path());

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Generic, None).unwrap();

        assert!(output.text.contains("[PASS] readme: README is present"));
        assert!(output.text.contains("Profiles: none"));
        assert!(!output.text.contains("rust_cargo_name"));
    }

    #[test]
    fn explicit_rust_profile_runs_rust_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        write_rust_fixture(temp_dir.path());

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Rust, None).unwrap();

        assert!(output.text.contains("[PASS] rust_cargo_name"));
    }

    #[test]
    fn empty_repository_only_runs_core_checks_in_auto_mode() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[WARN] readme"));
        assert!(!output.text.contains("rust_"));
        assert!(!output.text.contains("node_"));
        assert!(!output.text.contains("python_"));
        assert!(!output.text.contains("go_"));
        assert!(!output.text.contains("docker_"));
        assert!(!output.text.contains("jvm_"));
        assert!(!output.text.contains("deno_"));
        assert!(!output.text.contains("bun_"));
        assert!(!output.text.contains("dotnet_"));
        assert!(!output.text.contains("php_"));
        assert!(!output.text.contains("ruby_"));
        assert!(!output.text.contains("cpp_"));
        assert!(!output.text.contains("swift_"));
        assert!(!output.text.contains("kotlin_"));
    }

    #[test]
    fn explicit_node_profile_runs_node_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("package.json"),
            r#"{
  "name": "demo",
  "version": "0.1.0",
  "description": "Demo package",
  "license": "MIT",
  "repository": "https://example.com/demo",
  "scripts": { "test": "node --test" },
  "engines": { "node": ">=20" }
}"#,
        )
        .unwrap();
        fs::write(temp_dir.path().join("package-lock.json"), "{}\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Node, None).unwrap();

        assert!(output.text.contains("[PASS] node_name"));
        assert!(output.text.contains("[PASS] node_lockfile"));
    }

    #[test]
    fn explicit_python_profile_runs_python_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("pyproject.toml"),
            r#"[project]
name = "demo"
version = "0.1.0"
description = "Demo package"
readme = "README.md"
license = "MIT"

[build-system]
requires = ["setuptools"]
"#,
        )
        .unwrap();
        fs::write(temp_dir.path().join("README.md"), "# Demo\n").unwrap();
        fs::write(temp_dir.path().join("uv.lock"), "\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Python, None).unwrap();

        assert!(output.text.contains("[PASS] python_name"));
        assert!(output.text.contains("[PASS] python_build_system"));
    }

    #[test]
    fn explicit_go_profile_runs_go_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("go.mod"),
            "module example.com/demo\n\ngo 1.22\n",
        )
        .unwrap();
        fs::write(temp_dir.path().join("go.sum"), "\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Go, None).unwrap();

        assert!(output.text.contains("[PASS] go_module"));
        assert!(output.text.contains("[PASS] go_version"));
    }

    #[test]
    fn explicit_docker_profile_runs_container_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(temp_dir.path().join("Dockerfile"), "FROM alpine:3.20\n").unwrap();
        fs::write(temp_dir.path().join(".dockerignore"), "target\n").unwrap();
        fs::write(temp_dir.path().join("compose.yml"), "services: {}\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Docker, None).unwrap();

        assert!(output.text.contains("[PASS] docker_build_file"));
        assert!(output.text.contains("[PASS] docker_base_image_pin"));
    }

    #[test]
    fn auto_profile_runs_docker_checks_when_dockerfile_exists() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(temp_dir.path().join("Dockerfile"), "FROM alpine:latest\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("Profiles: docker"));
        assert!(output.text.contains("[WARN] docker_base_image_pin"));
    }

    #[test]
    fn explicit_jvm_profile_runs_maven_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("pom.xml"),
            "<project><groupId>com.example</groupId><artifactId>demo</artifactId><version>0.1.0</version></project>",
        )
        .unwrap();
        fs::write(temp_dir.path().join("mvnw"), "#!/bin/sh\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Jvm, None).unwrap();

        assert!(output.text.contains("[PASS] jvm_build_file"));
        assert!(output.text.contains("[PASS] jvm_maven_artifact_id"));
    }

    #[test]
    fn explicit_deno_profile_runs_deno_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("deno.json"),
            r#"{ "tasks": { "test": "deno test" } }"#,
        )
        .unwrap();
        fs::write(temp_dir.path().join("deno.lock"), "{}\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Deno, None).unwrap();

        assert!(output.text.contains("[PASS] deno_config"));
        assert!(output.text.contains("[PASS] deno_tasks"));
    }

    #[test]
    fn explicit_bun_profile_runs_bun_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("package.json"),
            r#"{
  "name": "demo",
  "packageManager": "bun@1.2.0",
  "scripts": { "test": "bun test" }
}"#,
        )
        .unwrap();
        fs::write(temp_dir.path().join("bun.lock"), "\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Bun, None).unwrap();

        assert!(output.text.contains("[PASS] bun_lockfile"));
        assert!(output.text.contains("[PASS] bun_package_manager"));
    }

    #[test]
    fn explicit_dotnet_profile_runs_dotnet_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(temp_dir.path().join("Demo.sln"), "\n").unwrap();
        fs::write(temp_dir.path().join("Demo.Tests.csproj"), "<Project />\n").unwrap();
        fs::write(temp_dir.path().join("global.json"), "{}\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Dotnet, None).unwrap();

        assert!(output.text.contains("[PASS] dotnet_project"));
        assert!(output.text.contains("[PASS] dotnet_tests"));
    }

    #[test]
    fn explicit_php_profile_runs_php_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("composer.json"),
            r#"{
  "name": "example/demo",
  "description": "Demo",
  "license": "MIT",
  "require": { "php": "^8.3" },
  "scripts": { "test": "phpunit" }
}"#,
        )
        .unwrap();
        fs::write(temp_dir.path().join("composer.lock"), "{}\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Php, None).unwrap();

        assert!(output.text.contains("[PASS] php_name"));
        assert!(output.text.contains("[PASS] php_composer_lock"));
    }

    #[test]
    fn explicit_ruby_profile_runs_ruby_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("Gemfile"),
            "source 'https://rubygems.org'\n",
        )
        .unwrap();
        fs::write(temp_dir.path().join("Gemfile.lock"), "\n").unwrap();
        fs::write(
            temp_dir.path().join("demo.gemspec"),
            "Gem::Specification.new\n",
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Ruby, None).unwrap();

        assert!(output.text.contains("[PASS] ruby_gemfile"));
        assert!(output.text.contains("[PASS] ruby_gemspec"));
    }

    #[test]
    fn explicit_cpp_profile_runs_cpp_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(temp_dir.path().join("CMakeLists.txt"), "project(demo)\n").unwrap();
        fs::write(temp_dir.path().join("compile_commands.json"), "[]\n").unwrap();
        fs::write(temp_dir.path().join("vcpkg.json"), "{}\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Cpp, None).unwrap();

        assert!(output.text.contains("[PASS] cpp_build_system"));
        assert!(output.text.contains("[PASS] cpp_tooling_metadata"));
    }

    #[test]
    fn explicit_swift_profile_runs_swift_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("Package.swift"),
            "// swift-tools-version: 6.0\n",
        )
        .unwrap();
        fs::write(temp_dir.path().join("Package.resolved"), "{}\n").unwrap();
        fs::create_dir(temp_dir.path().join("Tests")).unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Swift, None).unwrap();

        assert!(output.text.contains("[PASS] swift_package"));
        assert!(output.text.contains("[PASS] swift_tests"));
    }

    #[test]
    fn explicit_kotlin_profile_runs_kotlin_checks() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("build.gradle.kts"),
            "plugins { kotlin(\"jvm\") version \"2.2.0\" }\n",
        )
        .unwrap();
        fs::create_dir_all(temp_dir.path().join("src/main/kotlin")).unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Kotlin, None).unwrap();

        assert!(output.text.contains("[PASS] kotlin_build_file"));
        assert!(output.text.contains("[PASS] kotlin_plugin"));
    }

    #[test]
    fn legacy_python_profile_reports_legacy_files() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("setup.py"),
            "from setuptools import setup\n",
        )
        .unwrap();
        fs::write(temp_dir.path().join("requirements.txt"), "pytest\n").unwrap();
        fs::create_dir(temp_dir.path().join("tests")).unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Python, None).unwrap();

        assert!(output.text.contains("[WARN] python_pyproject"));
        assert!(output.text.contains("[PASS] python_legacy_setup"));
        assert!(output.text.contains("[PASS] python_requirements"));
        assert!(output.text.contains("[PASS] python_tests"));
    }

    #[test]
    fn rejects_missing_repository_path() {
        let temp_dir = tempfile::tempdir().unwrap();
        let missing_path = temp_dir.path().join("missing");

        let error =
            check_repository(&missing_path, OutputFormat::Text, Profile::Auto, None).unwrap_err();

        assert_eq!(
            error.to_string(),
            format!("repository path does not exist: {}", missing_path.display())
        );
    }

    #[test]
    fn rejects_file_repository_path() {
        let temp_dir = tempfile::tempdir().unwrap();
        let file_path = temp_dir.path().join("README.md");
        fs::write(&file_path, "# Test\n").unwrap();

        let error =
            check_repository(&file_path, OutputFormat::Text, Profile::Auto, None).unwrap_err();

        assert_eq!(
            error.to_string(),
            format!(
                "repository path is not a directory: {}",
                file_path.display()
            )
        );
    }

    #[test]
    fn accepts_common_readme_and_license_names() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(temp_dir.path().join("README.txt"), "# Test\n").unwrap();
        fs::write(temp_dir.path().join("LICENSE.txt"), "MIT\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[PASS] readme: README is present"));
        assert!(
            output
                .text
                .contains("[PASS] license: License file is present")
        );
    }

    #[test]
    fn warns_on_secret_like_files_and_allows_excluding_locations() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(temp_dir.path().join(".env"), "TOKEN=secret\n").unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();
        assert!(output.text.contains("[WARN] secret_like_file"));

        fs::write(
            temp_dir.path().join("repo-doctor.toml"),
            "exclude_paths = [\".env\"]\n",
        )
        .unwrap();
        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();
        assert!(!output.text.contains("secret_like_file"));
    }

    #[test]
    fn warns_when_workflows_directory_has_no_workflow_files() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(temp_dir.path().join(".github/workflows")).unwrap();
        fs::write(
            temp_dir.path().join(".github/workflows/README.md"),
            "# Workflows\n",
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(
            output
                .text
                .contains("[WARN] github_actions: Missing .github/workflows/*.yml or *.yaml")
        );
    }

    #[test]
    fn warns_when_workflow_yaml_is_invalid() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(temp_dir.path().join(".github/workflows")).unwrap();
        fs::write(
            temp_dir.path().join(".github/workflows/ci.yml"),
            "name: [broken\n",
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[WARN] github_actions_yaml"));
    }

    #[test]
    fn warns_when_rust_ci_commands_are_missing() {
        let temp_dir = tempfile::tempdir().unwrap();
        write_rust_fixture(temp_dir.path());
        fs::create_dir_all(temp_dir.path().join(".github/workflows")).unwrap();
        fs::write(
            temp_dir.path().join(".github/workflows/ci.yml"),
            "on:\n  pull_request:\n  push:\npermissions: {}\njobs: {}\n",
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[WARN] github_actions_rust_ci"));
    }

    #[test]
    fn warns_when_issue_template_frontmatter_is_missing() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(temp_dir.path().join(".github/ISSUE_TEMPLATE")).unwrap();
        fs::write(
            temp_dir.path().join(".github/ISSUE_TEMPLATE/bug_report.md"),
            "# Bug\n",
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[WARN] issue_template_frontmatter"));
    }

    #[test]
    fn fail_on_warn_sets_nonzero_exit_code() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output = check_repository(
            temp_dir.path(),
            OutputFormat::Text,
            Profile::Auto,
            Some(FailOn::Warn),
        )
        .unwrap();

        assert_eq!(output.exit_code, 1);
    }

    #[test]
    fn json_output_keeps_schema_version() {
        let temp_dir = tempfile::tempdir().unwrap();
        write_rust_fixture(temp_dir.path());

        let output =
            check_repository(temp_dir.path(), OutputFormat::Json, Profile::Auto, None).unwrap();
        let value: serde_json::Value = serde_json::from_str(&output.text).unwrap();

        assert_eq!(value.get("schema_version").unwrap(), 1);
        assert_eq!(value.get("selected_profiles").unwrap()[0], "rust");
        assert!(value.get("summary").unwrap().is_object());
        assert!(value.get("checks").unwrap().is_array());
        assert!(output.text.contains("\"id\": \"rust_cargo_name\""));
    }

    #[test]
    fn markdown_output_contains_summary_and_table() {
        let temp_dir = tempfile::tempdir().unwrap();
        write_rust_fixture(temp_dir.path());

        let output =
            check_repository(temp_dir.path(), OutputFormat::Markdown, Profile::Auto, None).unwrap();

        assert!(output.text.contains("# repo-doctor report"));
        assert!(output.text.contains("- Profiles: rust"));
        assert!(
            output
                .text
                .contains("| Status | Rule | Message | Remediation |")
        );
        assert!(output.text.contains("| PASS | `rust_cargo_name` |"));
    }

    #[test]
    fn github_annotation_output_emits_warnings_only() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Github, Profile::Auto, None).unwrap();

        assert!(output.text.contains("::warning title=readme::"));
        assert!(!output.text.contains("[PASS]"));
    }

    #[test]
    fn sarif_output_contains_warning_results() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Sarif, Profile::Auto, None).unwrap();
        let value: serde_json::Value = serde_json::from_str(&output.text).unwrap();

        assert_eq!(value.get("version").unwrap(), "2.1.0");
        assert_eq!(value["runs"][0]["tool"]["driver"]["name"], "repo-doctor");
        assert_eq!(value["runs"][0]["results"][0]["ruleId"], "readme");
    }

    #[test]
    fn compact_output_contains_one_line_summary() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Compact, Profile::Auto, None).unwrap();

        assert!(output.text.starts_with("repo-doctor path="));
        assert!(output.text.contains("score="));
        assert!(!output.text.contains('\n'));
    }

    #[test]
    fn junit_output_contains_failures_for_warnings() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Junit, Profile::Auto, None).unwrap();

        assert!(output.text.contains("<testsuite"));
        assert!(output.text.contains("<failure"));
    }

    #[test]
    fn warnings_only_filters_passes() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output = check_repository_with_options(
            temp_dir.path(),
            OutputFormat::Text,
            Profile::Auto,
            None,
            CheckOptions {
                fail_on: None,
                warnings_only: true,
                min_score: None,
                baseline: None,
            },
        )
        .unwrap();

        assert!(output.text.contains("[WARN] readme"));
        assert!(!output.text.contains("[PASS]"));
    }

    #[test]
    fn min_score_can_fail_quality_gate() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output = check_repository_with_options(
            temp_dir.path(),
            OutputFormat::Text,
            Profile::Auto,
            None,
            CheckOptions {
                fail_on: None,
                warnings_only: false,
                min_score: Some(100),
                baseline: None,
            },
        )
        .unwrap();

        assert_eq!(output.exit_code, 1);
    }

    #[test]
    fn list_commands_include_profiles_and_rules() {
        assert!(list_profiles().contains("rust\tCargo.toml"));
        assert!(list_rules().contains("readme\twarning"));
    }

    #[test]
    fn explain_rule_describes_known_rule() {
        let output = explain_rule("readme").unwrap();

        assert!(output.text.contains("Rule: readme"));
        assert!(output.text.contains("README is present"));
    }

    #[test]
    fn config_validate_reports_unknown_rules() {
        let temp_dir = tempfile::tempdir().unwrap();
        let config_path = temp_dir.path().join("repo-doctor.toml");
        fs::write(
            &config_path,
            r#"[[rules]]
id = "nope"
severity = "warning"
"#,
        )
        .unwrap();

        let output = validate_config_file(&config_path).unwrap();

        assert_eq!(output.exit_code, 1);
        assert!(output.text.contains("unknown rule id: nope"));
    }

    #[test]
    fn baseline_suppresses_existing_warning_ids() {
        let temp_dir = tempfile::tempdir().unwrap();
        let baseline_path = temp_dir.path().join("baseline.json");
        fs::write(&baseline_path, "[\"readme\"]").unwrap();

        let output = check_repository_with_options(
            temp_dir.path(),
            OutputFormat::Text,
            Profile::Auto,
            None,
            CheckOptions {
                fail_on: None,
                warnings_only: true,
                min_score: None,
                baseline: Some(&baseline_path),
            },
        )
        .unwrap();

        assert!(!output.text.contains("[WARN] readme"));
        assert!(output.text.contains("[WARN] license"));
    }

    #[test]
    fn html_output_contains_report_document() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Html, Profile::Auto, None).unwrap();

        assert!(output.text.contains("<!doctype html>"));
        assert!(output.text.contains("repo-doctor report"));
    }

    #[test]
    fn config_can_disable_rules_with_rationale() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("repo-doctor.toml"),
            r#"[[rules]]
id = "readme"
disabled = true
reason = "Fixture intentionally omits docs."
"#,
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(!output.text.contains("[WARN] readme"));
        assert!(output.text.contains("[WARN] license"));
    }

    #[test]
    fn config_rejects_disabled_rules_without_rationale_as_warning() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("repo-doctor.toml"),
            r#"[[rules]]
id = "readme"
disabled = true
"#,
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("[WARN] readme"));
        assert!(output.text.contains("[WARN] config_disabled_rule_reason"));
    }

    #[test]
    fn config_profiles_are_used_when_cli_profile_is_auto() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("repo-doctor.toml"),
            r#"profiles = ["rust"]"#,
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("Profiles: rust"));
        assert!(output.text.contains("[WARN] rust_cargo_toml"));
    }

    #[test]
    fn init_creates_starter_config() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output = init_config(temp_dir.path(), false).unwrap();

        assert!(output.text.contains("repo-doctor.toml"));
        assert!(temp_dir.path().join("repo-doctor.toml").exists());
    }

    #[test]
    fn init_full_creates_support_files() {
        let temp_dir = tempfile::tempdir().unwrap();

        let output = init_config(temp_dir.path(), true).unwrap();

        assert!(output.text.contains(".editorconfig"));
        assert!(temp_dir.path().join(".github/workflows/ci.yml").exists());
    }

    #[test]
    fn rust_lib_preset_selects_rust_and_suppresses_lockfile_warning() {
        let temp_dir = tempfile::tempdir().unwrap();
        fs::write(
            temp_dir.path().join("repo-doctor.toml"),
            r#"presets = ["rust-lib"]"#,
        )
        .unwrap();
        fs::write(
            temp_dir.path().join("Cargo.toml"),
            r#"[package]
name = "demo"
version = "0.1.0"
edition = "2024"
"#,
        )
        .unwrap();

        let output =
            check_repository(temp_dir.path(), OutputFormat::Text, Profile::Auto, None).unwrap();

        assert!(output.text.contains("Profiles: rust"));
        assert!(!output.text.contains("rust_cargo_lock"));
    }

    #[test]
    fn generates_bash_completions() {
        let output = completions(Shell::Bash).unwrap();
        let function_name = format!("_{}", env!("CARGO_PKG_NAME"));

        assert!(output.contains(&function_name));
    }

    #[test]
    fn generates_man_page() {
        let output = man_page().unwrap();
        let package_name = env!("CARGO_PKG_NAME");
        let escaped_name = package_name.replace('-', "\\-");

        assert!(output.contains(&format!(".TH {package_name}")));
        assert!(output.contains(&escaped_name));
    }

    fn write_rust_fixture(path: &Path) {
        fs::write(
            path.join("README.md"),
            "# Test\n\nRun `test --help` and `cargo test`.\n",
        )
        .unwrap();
        fs::write(path.join("LICENSE"), "MIT\n").unwrap();
        fs::write(path.join(".gitignore"), "/target\n").unwrap();
        fs::write(
            path.join("Cargo.toml"),
            r#"[package]
name = "test"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
description = "Test package"
repository = "https://example.com/test"
readme = "README.md"
license = "MIT"
"#,
        )
        .unwrap();
        fs::write(path.join("Cargo.lock"), "# lock\n").unwrap();
    }
}
